services:
  bookmarker-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookmarkerappdb
    ports:
      - "15432:5432" #"HOST_PORT_NUMBER : CONTAINER_SERVICE_PORT_NUMBER"
