# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: ["**"]

jobs:
  build:
    name: Build Bookmarker App
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Verify the build
#        run: mvn -B package --file pom.xml
        run: ./mvnw verify

      - name: Build and Publish Docker Image
        run:  |
          ./mvnw clean package jib:build -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
          docker push ${{ secrets.DOCKER.USERNAME }}/bookmarkerapp

        env:
          GITHUB_TOKEN: ${{ github.token }}
